### ISSUE TITLE
Instructions on module installation and usage

### ISSUE THREAD

**Issue by parasdsingh** [concierge/boss#1]
Could I get some instructions on how-to use this module?
I tried installing it via kpm but it failed with the following error(s)

**Debug Log**
```
Loading module 'boss'... 
Installing "express" from npm.
Installation complete.
Installing "basic-auth" from npm.
Installation complete.
Installing "sha512" from npm.
Installation complete.
Missing i18n value for key "Module is not one of the defined module types." in {current: "en", default:"en"}.
Error: Module is not one of the defined module types.
  at /root/Dev/concierge/core/modules/kassy/kassyModule.js:91:27
  at Object.exports.loadModule (/root/Dev/concierge/core/modules/kassy/kassyModule.js:94:35)
  at ModuleLoader._loadModuleInternal (/root/Dev/concierge/core/modules/modules.js:31:59)
  at ModuleLoader.loadModule (/root/Dev/concierge/core/modules/modules.js:118:27)
  at /root/Dev/concierge/modules/kpm/src/commands/install.js:40:48
  at doneOne (/root/Dev/concierge/node_modules/fs-extra/lib/copy/ncp.js:237:40)
  at /root/Dev/concierge/node_modules/fs-extra/lib/copy/ncp.js:122:11
  at /root/Dev/concierge/node_modules/graceful-fs/polyfills.js:219:18
  at FSReqWrap.oncomplete (fs.js:82:15)

Missing i18n value for key "Loading Failed" in {current: "en", default:"en"}.
Loading Failed
Error: Could not load module 'boss'. Does it have a syntax error?
  at Object.exports.loadModule (/root/Dev/concierge/core/modules/kassy/kassyModule.js:98:15)
  at ModuleLoader._loadModuleInternal (/root/Dev/concierge/core/modules/modules.js:31:59)
  at ModuleLoader.loadModule (/root/Dev/concierge/core/modules/modules.js:118:27)
  at /root/Dev/concierge/modules/kpm/src/commands/install.js:40:48
  at doneOne (/root/Dev/concierge/node_modules/fs-extra/lib/copy/ncp.js:237:40)
  at /root/Dev/concierge/node_modules/fs-extra/lib/copy/ncp.js:122:11
  at /root/Dev/concierge/node_modules/graceful-fs/polyfills.js:219:18
  at FSReqWrap.oncomplete (fs.js:82:15)

Module "boss" could not be loaded.
```

**Comment by drkno** [comment]
Boss is still very much a WIP (not much progress has been made as it depends on features that were not in Concierge until this week), it doesn't work at this time and has not been tested with 4.0-beta.0+. ATM it is just a modulised version of the node.js server behind [Wudhagh](https://github.com/mrkno/wudhagh).

The specific error from the stacktrace could be fixed by either removing line https://github.com/concierge/boss/blob/master/boss.js#L38 or adding `"type":"service"` to the `kassy.json`.

**Comment by parasdsingh** [comment]
Thank you for the directions. I did a local patch; ([`exports.__folderPath` ](https://github.com/concierge/boss/blob/master/boss.js#L18) was returning `undefined` for some reason) Hard-coded `folderPath` and managed to run the module 👍 

Looking forward to it's release 😀
