### ISSUE TITLE
All boss shows is an error

### ISSUE THREAD

**Issue by Mrs-Feathers** [concierge/boss#3]
Going to localhost:8080 just shows an error. dont know whats wrong. possibly outdated?

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 1. Received 4
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readUInt32BE (internal/buffer.js:192:5)
    at Function.WordArray.fromBuffer (/root/boss/node_modules/sha512/lib/word-array.js:95:19)
    at subtype.init.finalize (/root/boss/node_modules/sha512/lib/cryptojs.js:273:33)
    at /root/boss/node_modules/sha512/lib/cryptojs.js:300:35
    at module.exports.validateUser (/root/boss/server/users/users.js:11:20)
    at /root/boss/server/server/auth.js:29:25
    at Layer.handle [as handle_request] (/root/boss/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/boss/node_modules/express/lib/router/index.js:317:13)
    at /root/boss/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/boss/node_modules/express/lib/router/index.js:335:12)
    at next (/root/boss/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/root/boss/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/root/boss/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/boss/node_modules/express/lib/router/index.js:317:13)
    at /root/boss/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/boss/node_modules/express/lib/router/index.js:335:12)
    at next (/root/boss/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/root/boss/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/root/boss/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/boss/node_modules/express/lib/router/index.js:317:13)
    at /root/boss/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/boss/node_modules/express/lib/router/index.js:335:12)
    at next (/root/boss/node_modules/express/lib/router/index.js:275:10)
    at query (/root/boss/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/root/boss/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/root/boss/node_modules/express/lib/router/index.js:317:13)
    at /root/boss/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/root/boss/node_modules/express/lib/router/index.js:335:12)
    at next (/root/boss/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/root/boss/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/root/boss/node_modules/express/lib/application.js:174:10)
    at Server.app (/root/boss/node_modules/express/lib/express.js:39:9)
    at Server.<anonymous> (/root/boss/node_modules/engine.io/lib/server.js:473:22)
    at Server.<anonymous> (/root/boss/node_modules/socket.io/lib/index.js:343:16)
    at Server.emit (events.js:198:13)
    at parserOnIncoming (_http_server.js:679:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by Mrs-Feathers** [comment]
this is just from visiting it after doing npm install concierge -g and letting it set itself up. no reconfigging or anything.
